### ISSUE TITLE
测试包没有问题正式打包报错了

### ISSUE THREAD

**Issue by zhouzhiguang** [luckybilly/CC#150]
java.lang.RuntimeException: Unable to get provider com.billy.cc.core.providers.CC_Provider_pushcore: java.lang.ClassNotFoundException: Didn't find class "com.billy.cc.core.providers.CC_Provider_pushcore" on path: DexPathList[[zip file "/data/app/com.fude.discover-1/base.apk"],nativeLibraryDirectories=[/data/app/com.fude.discover-1/lib/arm64, /vendor/lib64, /system/lib64]]

**Comment by zhouzhiguang** [comment]
多谢齐哥的帮忙已经解决

**Comment by JGWCoding** [comment]
java.lang.RuntimeException: Unable to get provider com.billy.cc.core.component.remote.RemoteProvider: java.lang.ClassNotFoundException: Didn't find class "com.billy.cc.core.component.remote.RemoteProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.eebbk.vtraining-7qox2ur7ffI2XxzGtMV5nw==/base.apk"],nativeLibraryDirectories=[/data/app/com.eebbk.vtraining-7qox2ur7ffI2XxzGtMV5nw==/lib/arm64, /data/app/com.eebbk.vtraining-7qox2ur7ffI2XxzGtMV5nw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6638)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6159)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6063)
        at android.app.ActivityThread.access$1300(ActivityThread.java:208)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:222)
        at android.app.ActivityThread.main(ActivityThread.java:6911)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:505)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:905)

**Comment by JGWCoding** [comment]
> java.lang.RuntimeException: Unable to get provider com.billy.cc.core.providers.CC_Provider_pushcore: java.lang.ClassNotFoundException: Didn't find class "com.billy.cc.core.providers.CC_Provider_pushcore" on path: DexPathList[[zip file "/data/app/com.fude.discover-1/base.apk"],nativeLibraryDirectories=[/data/app/com.fude.discover-1/lib/arm64, /vendor/lib64, /system/lib64]]

能问下 怎么解决的吗
