### ISSUE TITLE
业务组件调试时,出现找不到cc的类,时好时坏

### ISSUE THREAD

**Issue by piratejason** [luckybilly/CC#176]
java.lang.RuntimeException: Unable to get provider com.billy.cc.core.component.remote.RemoteProvider: java.lang.ClassNotFoundException: Didn't find class "com.billy.cc.core.component.remote.RemoteProvider" on path: DexPathList[[zip file "/data/app/com.***.***-1/base.apk"],nativeLibraryDirectories=[/data/app/com.***.***-1/lib/arm64, /data/app/com.***.***-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6116)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5693)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5632)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1732)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6378)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1099)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

**Comment by JGWCoding** [comment]
java.lang.RuntimeException: Unable to get provider com.billy.cc.core.component.remote.RemoteProvider: java.lang.ClassNotFoundException: Didn't find class "com.billy.cc.core.component.remote.RemoteProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.eebbk.vtraining-7qox2ur7ffI2XxzGtMV5nw==/base.apk"],nativeLibraryDirectories=[/data/app/com.eebbk.vtraining-7qox2ur7ffI2XxzGtMV5nw==/lib/arm64, /data/app/com.eebbk.vtraining-7qox2ur7ffI2XxzGtMV5nw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6638)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6159)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6063)
        at android.app.ActivityThread.access$1300(ActivityThread.java:208)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:222)
        at android.app.ActivityThread.main(ActivityThread.java:6911)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:505)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:905)

**Comment by JGWCoding** [comment]
引用微信的matrix框架出现该问题
