### ISSUE TITLE
找不到CCUtil

### ISSUE THREAD

**Issue by wangchaoAndroid** [luckybilly/CC#54]
华为荣耀honor h30-L01  ，android版本 4.4.2  初始化时候崩溃
`E/AndroidRuntime: FATAL EXCEPTION: main
 java.lang.NoClassDefFoundError: com.billy.cc.core.component.CCUtil
                 at com.billy.cc.core.component.CC.<clinit>(CC.java:67)
                 at com.cop.filesearch.MyApp.onCreate(MyApp.java:29)
                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1009)
                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4621)
                 at android.app.ActivityThread.access$1800(ActivityThread.java:138)
                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1299)
                     at android.os.Handler.dispatchMessage(Handler.java:102)
                     at android.os.Looper.loop(Looper.java:136)
                     at android.app.ActivityThread.main(ActivityThread.java:5297)
                     at java.lang.reflect.Method.invokeNative(Native Method)
                     at java.lang.reflect.Method.invoke(Method.java:515)
                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:851)
                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:667)
                     at dalvik.system.NativeStart.main(Native Method)`

**Comment by wangchaoAndroid** [comment]
MultiDex
